services:
  qc-essence-scraper:
    container_name: qc-essence-scraper
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./db:/app/db
      - ./templates:/app/templates
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
